theme = 'rose_pine'
[editor]
true-color = true
line-number = 'relative'
rulers = [80]
bufferline = 'always'
[keys.normal]
esc = ['collapse_selection', 'keep_primary_selection']
C-p = ['move_line_up', 'scroll_up']
C-n = ['move_line_down', 'scroll_down']
C-f = [":new", ":insert-output lf-pick",":theme default", "select_all"]
[editor.cursor-shape]
insert = 'bar'
normal = 'block'
select = 'underline'

[editor.file-picker]
hidden = false
